import { Post } from "./types";

export const trendingPosts: Post[] = [
  {
    id: "t1",
    title: "Nimbus — collaborative whiteboard for remote teams",
    status: "Recruiting",
    companyName: "Nimbus Labs",
    category: "Design Tools",
    authorName: "Maya Chen",
    postedAgo: "2d ago",
    description:
      "Real-time canvas with infinite zoom, live cursors, and version history. Looking for a founding design partner to shape the v1 interaction model.",
    tags: ["SaaS", "Design Tools", "Remote Work"],
    roles: [
      {
        title: "Product Designer",
        compType: "Equity",
        compValue: "1.5%",
        employment: "Part-time",
        filled: 0,
        total: 1,
        description:
          "Own the interaction model for an infinite canvas — pan/zoom behavior, live-cursor presence, and how selection and grouping feel at speed. You'll work directly off Figma files we already have and ship real spec-ready flows, not just mood boards.",
        requirements: [
          "3+ years designing complex, high-interaction products",
          "Portfolio with at least one canvas, editor, or spatial UI",
          "Comfortable prototyping in Figma or code to test motion",
        ],
      },
      {
        title: "Frontend Engineer",
        compType: "Equity",
        compValue: "2%",
        employment: "Full-time",
        filled: 1,
        total: 2,
        description:
          "Build and optimize the real-time canvas rendering layer — WebGL/Canvas performance, cursor sync over CRDTs, and smooth zoom at thousands of objects. You'll pair closely with the founding engineer on architecture decisions.",
        requirements: [
          "Strong TypeScript + React fundamentals",
          "Experience with Canvas, WebGL, or a similar rendering layer",
          "Bonus: shipped a CRDT or OT-based collaborative feature",
        ],
      },
    ],
    team: [
      { initials: "MC", name: "Maya Chen", role: "Co-founder, Product" },
      { initials: "JP", name: "Jordan Park", role: "Co-founder, Engineering" },
    ],
    extraMembers: 1,
    location: "Remote",
    employment: "Contract",
  },
  {
    id: "t2",
    title: "Fieldnote",
    status: "Hiring",
    companyName: "Fieldnote",
    category: "Mobile",
    authorName: "Alex Rivera",
    postedAgo: "5h ago",
    description: "Voice-first note capture for researchers doing fieldwork without signal.",
    tags: ["Mobile", "AI"],
    roles: [
      {
        title: "iOS Engineer",
        compType: "Revenue-share",
        compValue: "3%",
        employment: "Full-time",
        filled: 0,
        total: 1,
        description:
          "Build the offline-first capture pipeline — on-device transcription, background sync when signal returns, and a battery-conscious recording UI researchers can trust in the field for hours at a time.",
        requirements: [
          "Shipped at least one App Store app solo or as lead",
          "Comfortable with Core Data / offline-first architecture",
          "Interest in on-device ML (Whisper.cpp or similar) is a plus",
        ],
      },
    ],
    team: [{ initials: "AR", name: "Alex Rivera", role: "Founder" }],
    location: "Austin, TX",
    employment: "Full-time",
  },
  {
    id: "t3",
    title: "Ledgerly — bookkeeping automation for freelancers",
    status: "In Progress",
    companyName: "Ledgerly",
    category: "Fintech",
    authorName: "Priya Nair",
    postedAgo: "1w ago",
    description:
      "Auto-categorized transactions, quarterly tax estimates, and one-click invoice reconciliation, built specifically for solo freelancers who hate spreadsheets.",
    tags: ["Fintech", "B2C", "Automation"],
    roles: [
      {
        title: "Backend Engineer",
        compType: "Equity",
        compValue: "2.5%",
        employment: "Full-time",
        filled: 1,
        total: 1,
        description:
          "Own the transaction-categorization pipeline and Plaid integration, plus the quarterly tax-estimate engine. This role is filled but we keep the details visible for transparency.",
        requirements: [
          "Experience with Plaid or a comparable banking API",
          "Strong grasp of async job processing at scale",
        ],
      },
      {
        title: "Growth Marketer",
        compType: "Equity",
        compValue: "1%",
        employment: "Part-time",
        filled: 0,
        total: 1,
        description:
          "Run acquisition experiments aimed at solo freelancers — content, SEO, and small-scale paid tests. You'll own the funnel from first touch to activated account.",
        requirements: [
          "Track record running growth loops for a consumer or B2C product",
          "Comfortable analyzing funnel data without a dedicated analyst",
        ],
      },
      {
        title: "Customer Support",
        compType: "Cash",
        compValue: "$20/hr",
        employment: "Part-time",
        filled: 0,
        total: 2,
        description:
          "Answer inbound support tickets from freelancers navigating tax season, and flag recurring pain points back to product. Flexible hours, async-friendly.",
        requirements: [
          "Clear written communication",
          "Basic comfort with bookkeeping or tax terminology preferred",
        ],
      },
    ],
    team: [
      { initials: "PN", name: "Priya Nair", role: "Founder & CEO" },
      { initials: "DK", name: "Devon Kim", role: "Engineering Lead" },
      { initials: "SL", name: "Sara Lin", role: "Product" },
    ],
    extraMembers: 2,
    location: "New York, NY",
    employment: "Full-time",
  },
  {
    id: "t4",
    title: "Trailhead",
    status: "Closed",
    companyName: "Trailhead",
    category: "Outdoors",
    authorName: "Sam Osei",
    postedAgo: "3w ago",
    description: "Offline-first hiking route planner with community trail conditions.",
    tags: ["Outdoors", "Mobile"],
    roles: [],
    team: [{ initials: "SO", name: "Sam Osei", role: "Founder" }],
    location: "Denver, CO",
    employment: "Contract",
  },
  {
    id: "t5",
    title: "Chorus — async standups for distributed teams",
    status: "Recruiting",
    companyName: "Chorus",
    category: "Productivity",
    authorName: "Liam Brooks",
    postedAgo: "1d ago",
    description:
      "Short video check-ins that auto-summarize into a written digest, so teams across time zones stay in sync without another live meeting.",
    tags: ["Productivity", "SaaS"],
    roles: [
      {
        title: "Full-stack Engineer",
        compType: "Equity",
        compValue: "3%",
        employment: "Full-time",
        filled: 0,
        total: 1,
        description:
          "Build end-to-end: the async video-capture flow, the summarization pipeline, and the digest views teams read every morning. You'll set a lot of the early technical direction.",
        requirements: [
          "Comfortable owning both frontend and backend for a feature",
          "Experience with video upload/processing pipelines a plus",
          "Product sense — you'll help shape the roadmap, not just execute it",
        ],
      },
      {
        title: "UI Designer",
        compType: "Equity",
        compValue: "1.5%",
        employment: "Part-time",
        filled: 0,
        total: 1,
        description:
          "Design the daily digest experience — how a week of scattered video check-ins turns into something a manager can scan in 90 seconds. Heavy focus on information hierarchy and clarity.",
        requirements: [
          "Portfolio showing dashboard or digest/summary-style UI",
          "Fluency in Figma component systems",
        ],
      },
    ],
    team: [{ initials: "LB", name: "Liam Brooks", role: "Founder" }],
    location: "Remote",
    employment: "Full-time",
  },
  {
    id: "t6",
    title: "Pantry",
    status: "Hiring",
    companyName: "Pantry",
    category: "Consumer",
    authorName: "Noor Ahmed",
    postedAgo: "4d ago",
    description: "Meal planning that works backward from what's already in your fridge.",
    tags: ["Consumer", "AI"],
    roles: [
      {
        title: "ML Engineer",
        compType: "Cash",
        compValue: "$45/hr",
        employment: "Part-time",
        filled: 0,
        total: 1,
        description:
          "Improve the fridge-photo → ingredient-list model and the recipe-ranking logic that turns leftovers into a plan. You'll work with a real (growing) dataset of user-submitted photos.",
        requirements: [
          "Experience with vision models (classification or detection)",
          "Practical experience shipping ML in a production app, not just notebooks",
        ],
      },
    ],
    team: [
      { initials: "NA", name: "Noor Ahmed", role: "Founder" },
      { initials: "TW", name: "Theo Walsh", role: "Design" },
    ],
    location: "Seattle, WA",
    employment: "Part-time",
  },
];

export const newPosts: Post[] = [
  {
    id: "n1",
    title: "Kindred — matchmaking for co-founders",
    status: "Recruiting",
    companyName: "Kindred",
    category: "Community",
    authorName: "Isabel Torres",
    postedAgo: "1h ago",
    description:
      "Structured compatibility interviews (not a swipe deck) to pair early-stage founders on working style, risk tolerance, and equity expectations before they commit.",
    tags: ["Startups", "Community", "Matching"],
    roles: [
      {
        title: "Backend Engineer",
        compType: "Equity",
        compValue: "2%",
        employment: "Full-time",
        filled: 0,
        total: 1,
        description:
          "Build the matching engine that scores compatibility across dozens of structured-interview signals, plus the scheduling and intro-flow backend.",
        requirements: [
          "Strong data modeling skills",
          "Comfortable designing a scoring/ranking system from scratch",
        ],
      },
      {
        title: "Community Lead",
        compType: "Equity",
        compValue: "1%",
        employment: "Part-time",
        filled: 0,
        total: 1,
        description:
          "Run the vetting calls, keep the founder pool high-signal, and build the early rituals (intro threads, matched-pair check-ins) that make the community feel curated, not cold.",
        requirements: [
          "Experience running or moderating a founder/startup community",
          "Excellent judgment reading people quickly and kindly",
        ],
      },
    ],
    team: [{ initials: "IT", name: "Isabel Torres", role: "Founder" }],
    location: "San Francisco, CA",
    employment: "Full-time",
  },
  {
    id: "n2",
    title: "Loop",
    status: "Recruiting",
    companyName: "Loop",
    category: "Health",
    authorName: "Kenji Watanabe",
    postedAgo: "6h ago",
    description: "Habit tracker that adapts its reminders to your actual sleep and calendar data.",
    tags: ["Health", "Mobile"],
    roles: [
      {
        title: "Mobile Engineer",
        compType: "Equity",
        compValue: "2%",
        employment: "Full-time",
        filled: 0,
        total: 1,
        description:
          "Build the reminder-scheduling engine that reads calendar + sleep signals (HealthKit/Health Connect) and decides when a nudge will actually land instead of getting swiped away.",
        requirements: [
          "Shipped a React Native or native mobile app end to end",
          "Experience with HealthKit or Health Connect a strong plus",
        ],
      },
    ],
    team: [{ initials: "KW", name: "Kenji Watanabe", role: "Founder" }],
    location: "Remote",
    employment: "Full-time",
  },
  {
    id: "n3",
    title: "Groundwork — permit tracking for small contractors",
    status: "In Progress",
    companyName: "Groundwork",
    category: "Construction",
    authorName: "Dana Wu",
    postedAgo: "12h ago",
    description:
      "A single dashboard for permit status, inspection scheduling, and code compliance across every jurisdiction a small contracting crew works in.",
    tags: ["Construction", "B2B", "SaaS"],
    roles: [
      {
        title: "Product Manager",
        compType: "Equity",
        compValue: "1.5%",
        employment: "Full-time",
        filled: 1,
        total: 1,
        description:
          "Owns the roadmap and talks to contractor crews every week to keep the dashboard grounded in how permitting actually works jurisdiction to jurisdiction.",
        requirements: ["Experience in vertical B2B SaaS", "Comfortable doing weekly customer calls"],
      },
      {
        title: "Sales Lead",
        compType: "Revenue-share",
        compValue: "4%",
        employment: "Full-time",
        filled: 0,
        total: 1,
        description:
          "Run the full-cycle sales motion for small contracting crews — from cold outreach through demo to close — and feed pricing/packaging learnings back to the team.",
        requirements: [
          "Full-cycle B2B sales experience, ideally in construction or field services",
          "Comfortable being the first sales hire with no existing playbook",
        ],
      },
    ],
    team: [
      { initials: "DW", name: "Dana Wu", role: "Founder & PM" },
      { initials: "RF", name: "Ravi Fernandez", role: "Engineering" },
      { initials: "MG", name: "Mia Garcia", role: "Design" },
    ],
    location: "Chicago, IL",
    employment: "Full-time",
  },
  {
    id: "n4",
    title: "Signal",
    status: "Hiring",
    companyName: "Signal",
    category: "Dev Tools",
    authorName: "Owen Clarke",
    postedAgo: "2d ago",
    description: "Alerting layer for indie hackers watching their infra dashboards at 2am.",
    tags: ["Dev Tools"],
    roles: [
      {
        title: "DevOps Engineer",
        compType: "Cash",
        compValue: "$50/hr",
        employment: "Contract",
        filled: 0,
        total: 1,
        description:
          "Harden the alert-ingestion pipeline (webhooks, on-call escalation, dedup logic) so a 2am spike gets to the right person once, not five times.",
        requirements: [
          "Experience running production alerting/on-call infrastructure",
          "Comfortable with queues and at-least-once delivery tradeoffs",
        ],
      },
    ],
    team: [{ initials: "OC", name: "Owen Clarke", role: "Founder" }],
    location: "Remote",
    employment: "Contract",
  },
  {
    id: "n5",
    title: "Harvest Table — CSA subscription management for small farms",
    status: "Recruiting",
    companyName: "Harvest Table",
    category: "Agtech",
    authorName: "Grace Lin",
    postedAgo: "3d ago",
    description:
      "Lets small farms run weekly CSA boxes without a spreadsheet: signups, pickup routing, seasonal swaps, and payment collection in one lightweight tool.",
    tags: ["Agtech", "Local", "B2B"],
    roles: [
      {
        title: "Frontend Engineer",
        compType: "Equity",
        compValue: "2%",
        employment: "Part-time",
        filled: 0,
        total: 1,
        description:
          "Build the farmer-facing dashboard for weekly box planning, seasonal swaps, and pickup-route views — designed for people checking it from a phone in a field.",
        requirements: ["Strong React fundamentals", "Care about usability for non-technical users"],
      },
      {
        title: "Ops Coordinator",
        compType: "Cash",
        compValue: "$25/hr",
        employment: "Part-time",
        filled: 0,
        total: 1,
        description:
          "Onboard new farms, help them set up their first CSA season in the tool, and be the friendly voice on support calls during pickup-day chaos.",
        requirements: ["Comfortable talking to non-technical small-business owners", "Organized and responsive"],
      },
    ],
    team: [{ initials: "GL", name: "Grace Lin", role: "Founder" }],
    location: "Portland, OR",
    employment: "Part-time",
  },
  {
    id: "n6",
    title: "Afterword",
    status: "Closed",
    companyName: "Afterword",
    category: "Reading",
    authorName: "Theo Marsh",
    postedAgo: "5d ago",
    description: "A quiet reading log for people who finish maybe six books a year.",
    tags: ["Reading", "Consumer"],
    roles: [],
    team: [{ initials: "TM", name: "Theo Marsh", role: "Founder" }],
    location: "Remote",
    employment: "Contract",
  },
];