import { Post } from "./types";

export const trendingPosts: Post[] = [
  {
    id: "t1",
    title: "Nimbus — collaborative whiteboard for remote teams",
    status: "Recruiting",
    authorName: "Maya Chen",
    postedAgo: "2d ago",
    description:
      "Real-time canvas with infinite zoom, live cursors, and version history. Looking for a founding design partner to shape the v1 interaction model.",
    tags: ["SaaS", "Design Tools", "Remote Work"],
    roles: [
      { title: "Product Designer", compType: "Equity", compValue: "1.5%", employment: "Part-time", filled: 0, total: 1 },
      { title: "Frontend Engineer", compType: "Equity", compValue: "2%", employment: "Full-time", filled: 1, total: 2 },
    ],
    team: [{ initials: "MC" }, { initials: "JP" }],
    extraMembers: 1,
    location: "Remote",
    employment: "Contract",
  },
  {
    id: "t2",
    title: "Fieldnote",
    status: "Hiring",
    authorName: "Alex Rivera",
    postedAgo: "5h ago",
    description: "Voice-first note capture for researchers doing fieldwork without signal.",
    tags: ["Mobile", "AI"],
    roles: [{ title: "iOS Engineer", compType: "Revenue-share", compValue: "3%", employment: "Full-time", filled: 0, total: 1 }],
    team: [{ initials: "AR" }],
    location: "Austin, TX",
    employment: "Full-time",
  },
  {
    id: "t3",
    title: "Ledgerly — bookkeeping automation for freelancers",
    status: "In Progress",
    authorName: "Priya Nair",
    postedAgo: "1w ago",
    description:
      "Auto-categorized transactions, quarterly tax estimates, and one-click invoice reconciliation, built specifically for solo freelancers who hate spreadsheets.",
    tags: ["Fintech", "B2C", "Automation"],
    roles: [
      { title: "Backend Engineer", compType: "Equity", compValue: "2.5%", employment: "Full-time", filled: 1, total: 1 },
      { title: "Growth Marketer", compType: "Equity", compValue: "1%", employment: "Part-time", filled: 0, total: 1 },
      { title: "Customer Support", compType: "Cash", compValue: "$20/hr", employment: "Part-time", filled: 0, total: 2 },
    ],
    team: [{ initials: "PN" }, { initials: "DK" }, { initials: "SL" }],
    extraMembers: 2,
    location: "New York, NY",
    employment: "Full-time",
  },
  {
    id: "t4",
    title: "Trailhead",
    status: "Closed",
    authorName: "Sam Osei",
    postedAgo: "3w ago",
    description: "Offline-first hiking route planner with community trail conditions.",
    tags: ["Outdoors", "Mobile"],
    roles: [],
    team: [{ initials: "SO" }],
    location: "Denver, CO",
    employment: "Contract",
  },
  {
    id: "t5",
    title: "Chorus — async standups for distributed teams",
    status: "Recruiting",
    authorName: "Liam Brooks",
    postedAgo: "1d ago",
    description:
      "Short video check-ins that auto-summarize into a written digest, so teams across time zones stay in sync without another live meeting.",
    tags: ["Productivity", "SaaS"],
    roles: [
      { title: "Full-stack Engineer", compType: "Equity", compValue: "3%", employment: "Full-time", filled: 0, total: 1 },
      { title: "UI Designer", compType: "Equity", compValue: "1.5%", employment: "Part-time", filled: 0, total: 1 },
    ],
    team: [{ initials: "LB" }],
    location: "Remote",
    employment: "Full-time",
  },
  {
    id: "t6",
    title: "Pantry",
    status: "Hiring",
    authorName: "Noor Ahmed",
    postedAgo: "4d ago",
    description: "Meal planning that works backward from what's already in your fridge.",
    tags: ["Consumer", "AI"],
    roles: [{ title: "ML Engineer", compType: "Cash", compValue: "$45/hr", employment: "Part-time", filled: 0, total: 1 }],
    team: [{ initials: "NA" }, { initials: "TW" }],
    location: "Seattle, WA",
    employment: "Part-time",
  },
];

export const newPosts: Post[] = [
  {
    id: "n1",
    title: "Kindred — matchmaking for co-founders",
    status: "Recruiting",
    authorName: "Isabel Torres",
    postedAgo: "1h ago",
    description:
      "Structured compatibility interviews (not a swipe deck) to pair early-stage founders on working style, risk tolerance, and equity expectations before they commit.",
    tags: ["Startups", "Community", "Matching"],
    roles: [
      { title: "Backend Engineer", compType: "Equity", compValue: "2%", employment: "Full-time", filled: 0, total: 1 },
      { title: "Community Lead", compType: "Equity", compValue: "1%", employment: "Part-time", filled: 0, total: 1 },
    ],
    team: [{ initials: "IT" }],
    location: "San Francisco, CA",
    employment: "Full-time",
  },
  {
    id: "n2",
    title: "Loop",
    status: "Recruiting",
    authorName: "Kenji Watanabe",
    postedAgo: "6h ago",
    description: "Habit tracker that adapts its reminders to your actual sleep and calendar data.",
    tags: ["Health", "Mobile"],
    roles: [{ title: "Mobile Engineer", compType: "Equity", compValue: "2%", employment: "Full-time", filled: 0, total: 1 }],
    team: [{ initials: "KW" }],
    location: "Remote",
    employment: "Full-time",
  },
  {
    id: "n3",
    title: "Groundwork — permit tracking for small contractors",
    status: "In Progress",
    authorName: "Dana Wu",
    postedAgo: "12h ago",
    description:
      "A single dashboard for permit status, inspection scheduling, and code compliance across every jurisdiction a small contracting crew works in.",
    tags: ["Construction", "B2B", "SaaS"],
    roles: [
      { title: "Product Manager", compType: "Equity", compValue: "1.5%", employment: "Full-time", filled: 1, total: 1 },
      { title: "Sales Lead", compType: "Revenue-share", compValue: "4%", employment: "Full-time", filled: 0, total: 1 },
    ],
    team: [{ initials: "DW" }, { initials: "RF" }, { initials: "MG" }],
    location: "Chicago, IL",
    employment: "Full-time",
  },
  {
    id: "n4",
    title: "Signal",
    status: "Hiring",
    authorName: "Owen Clarke",
    postedAgo: "2d ago",
    description: "Alerting layer for indie hackers watching their infra dashboards at 2am.",
    tags: ["Dev Tools"],
    roles: [{ title: "DevOps Engineer", compType: "Cash", compValue: "$50/hr", employment: "Contract", filled: 0, total: 1 }],
    team: [{ initials: "OC" }],
    location: "Remote",
    employment: "Contract",
  },
  {
    id: "n5",
    title: "Harvest Table — CSA subscription management for small farms",
    status: "Recruiting",
    authorName: "Grace Lin",
    postedAgo: "3d ago",
    description:
      "Lets small farms run weekly CSA boxes without a spreadsheet: signups, pickup routing, seasonal swaps, and payment collection in one lightweight tool.",
    tags: ["Agtech", "Local", "B2B"],
    roles: [
      { title: "Frontend Engineer", compType: "Equity", compValue: "2%", employment: "Part-time", filled: 0, total: 1 },
      { title: "Ops Coordinator", compType: "Cash", compValue: "$25/hr", employment: "Part-time", filled: 0, total: 1 },
    ],
    team: [{ initials: "GL" }],
    location: "Portland, OR",
    employment: "Part-time",
  },
  {
    id: "n6",
    title: "Afterword",
    status: "Closed",
    authorName: "Theo Marsh",
    postedAgo: "5d ago",
    description: "A quiet reading log for people who finish maybe six books a year.",
    tags: ["Reading", "Consumer"],
    roles: [],
    team: [{ initials: "TM" }],
    location: "Remote",
    employment: "Contract",
  },
];